### ISSUE TITLE
Actualizar la lectura de archivos

### ISSUE THREAD

**Issue by jorluos** [300CIS017-Object-Oriented-Programming/proyecto-2-snies-extractor-didi-sparty#7]
Actualizar la lectura de archivos teniendo en cuenta el polimorfismo y la posibilidad de que la disposición de las columnas cambie

**Comment by samuelbonillaf** [comment]
Para ello cambiar la clase ProgramaAcademico por un mapa (Sea colocarlo dentro de la clase o reemplazar la clase, depende de los metodos de gestor csv y controller) ademas  de las respectivas correcciones en la lectura

**Comment by jorluos** [comment]
cambiar la lectura de archivos a la clase padre FileManager y que la escritura quede en el gestor csv

**Comment by Alejost7** [comment]
He creado la clase base FileManager, a partir de esta he creado una clase derivada llamada CsvReader, que se encarga específicamente de la lectura, se han modificado otros módulos para la correcta implementación de esta separación. En conclusión se ha realizado una separación de responsabilidades entre lectura y escritura
